export const DOWNLOAD_BEGIN_STATE = "DOWNLOAD_BEGIN_STATE";
export const DOWNLOAD_SUCCESS_STATE = "DOWNLOAD_SUCCESS_STATE";
export const DOWNLOAD_END_STATE = "DOWNLOAD_END_STATE";

export const GET_VID_INFO_START = "GET_VID_INFO_START";
export const GET_VID_INFO_DONE = "GET_VID_INFO_DONE";
export const GET_VID_INFO_FAILED = "GET_VID_INFO_FAILED";
